### ISSUE TITLE
Unable to generate model file from swagger.yml using generator nodejs-express-server

### ISSUE THREAD

**Issue by Git-Hub-User-0** [OpenAPITools/openapi-generator-cli#384]
Hi,
I am unable to generate the models file in nodejs using the nodejs-express-server.

Even if i am trying with swagger example file, models file is not getting generated [petstore.swagger](https://petstore.swagger.io/v2/swagger.json)

package version: "@openapitools/openapi-generator-cli": "^2.3.4"

Using this command to generate models:
`openapi-generator-cli generate -g nodejs-express-server -i /openApi.yaml -o ./models --global-property models --generate-alias-as-model --enable-post-process-file`

Can you please help with this. 
How should i generate models file from swagger openApi 3.0.

Thanks in advance.

@kay-schecker

**Comment by kay-schecker** [comment]
# ⚠️ Important Notice

### Please differentiate the bug

This repository is not responsible for the actual code generation. If you have problems with the code generation, please open the bug at [OpenAPITools/openapi-generator](https://github.com/OpenAPITools/openapi-generator). 

Please also check if the bug is already known before you open a new bug.
