### ISSUE TITLE
[BUG] version-manager doesn't work since search.maven.org redirects to central.sonatype.com

### ISSUE THREAD

**Issue by ElieDeloumeau** [OpenAPITools/openapi-generator-cli#718]
# 🐛 Bug Report:

### Describe the bug
The `version-manager` sub-command doesn't work since search.maven.org redirects to central.sonatype.com

### Steps to Reproduce
```
openapi-generator-cli version-manager list
```

### Expected behavior
Outputs a list of available versions

### Screenshots
![image](https://github.com/OpenAPITools/openapi-generator-cli/assets/2671317/6bd6998a-41bf-4f76-bd24-f3b9214e5d6c)

### Operation System  (the problem is not related to OS):
 - OS: Manjaro Linux
 - Version 23

### Package System:
 - npm 9.6.7

### Additional context
https://search.maven.org now redirects to https://central.sonatype.com/

**Comment by Amber-Williams** [comment]
I have this issue occurring when using the npm package of `@openapitools/openapi-generator-cli` in general. This is causing our CI/CD pipelines to break. I've tried various node versions to get it to work locally without luck. Here's our main branch that hasn't changed failing a build today due to this that hasn't changed any parts related to this from what I can see 
<img width="1067" alt="image" src="https://github.com/OpenAPITools/openapi-generator-cli/assets/27780374/f3e6205f-b7d2-4cd4-b291-d6b3ce70fec8">

Using the the brew package instead is in fact working as expected however for me locally. So something with the NPM package has the issue that has deviated from the brew package

### Local set up
OS: MacOS Ventura 13.2.1
npm: 8.19.2
node: 18

**Comment by ElieDeloumeau** [comment]
It works now, redirect no longer happens on solrsearch
